### ISSUE TITLE
"Set string", "Set boolean" instead of correct controls

### ISSUE THREAD

**Issue by mariohamann** [Uscreen-video/cem-plugin-better-lit-types#4]
Hey,

first of all: Thanks for your work on this package! It literally came in the right moment! :) Hope to find some time to contribute in the future.

Coming to the issue: Select fields work great out of the box, but for booleans, strings etc. I first have to click "Set boolean" before being able to set the `arg`. Should I fix that on my side or is this something the plugin might do in future?

![CleanShot 2023-02-06 at 19 29 10](https://user-images.githubusercontent.com/26542182/217055290-987d8e4d-d07f-47c1-b7cb-c65080230eb0.gif)

Once again – thanks for your work!
Mario

**Comment by Bitaru** [comment]
Hey! Thank you for the response, I've faced such an issue too but haven't come up with an idea of how to fix it. Seems like in the new Storybook when you have an undefined value it renders such buttons https://github.com/storybookjs/storybook/blob/next/code/ui/blocks/src/controls/Boolean.tsx#L103

**Comment by mariohamann** [comment]
Thanks for the response, that helps me digging into the issue! Should be solvable with string fallback to `''` (if no default is set in the props) and boolean fallback to `false`.

Maybe as a config option as you solved it e.g. for the slot-wrappers.

Maybe these days I'll find the time for proposing a solution... let's see.

**Comment by mariohamann** [comment]
Found a different solution. In Storybook 7 you have to make sure to set `args`, in addition to  `argTypes`. I implemented some automatic `args` setter from props, CSS variables and slots.

Works fine for me and therefore IMO shouldn't be a bug of the package. Just reach out, if I should add some docs for that in the README.
