### ISSUE TITLE
issue creating a description

### ISSUE THREAD

**Issue by piotretm** [Uscreen-video/cem-plugin-better-lit-types#5]
Hi, 
I have an error while rendering the storybook docs. The property described in my `custom-elements.json` like that:
```
...
{
              "name": "uiSchema",
              "type": "object",
              "description": "Represents a layout element which can order its children\nin a specific way.",
              "fieldName": "uiSchema",
              "properties": {
                "elements": {
                  "description": "The child elements of this layout.",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/UISchemaElement"
                  }
                },
                "type": {
                  "description": "The type of this UI schema element.",
                  "type": "string"
                },
                "rule": {
                  "$ref": "#/definitions/Rule",
                  "description": "An optional rule."
                },
                "options": {
                  "description": "Any additional options.",
                  "type": "object",
                  "additionalProperties": {}
                }
              },
              "additionalProperties": false
            }
...
```
renders:
![image](https://github.com/Uscreen-video/cem-plugin-better-lit-types/assets/143094148/5984f8b2-2678-458f-9ff0-49c74b3be41f)
and there is an error in the console saying: "Warning: validateDOMNesting(...): \<details> cannot appear as a descendant of \<p>."

Any ideas how to approach this?

**Comment by Bitaru** [comment]
Hey @piotretm, it seems like there may be an issue with the item description. 
Let's try printing it for this property.
in `.storybook/preview.js`
```javascript
console.log(createArgsExtractor(customElements)('YOUR-COMPONENT').uiSchema.description)
```

**Comment by piotretm** [comment]
@Bitaru thanks for the quick response :)

this is the result of logging the mentioned property:
```
preview.ts:12 
Represents a layout element which can order its children
in a specific way.
<details>
  <summary>*Object properties*</summary>
  <ul>
  
    <li>
      <details>
        <summary>elements: `array`</summary>
        The child elements of this layout.
      </details>
    </li>
  

    <li>
      <details>
        <summary>type: `string`</summary>
        The type of this UI schema element.
      </details>
    </li>
  

    <li>
      <details>
        <summary>rule: `object`</summary>
        An optional rule.
      </details>
    </li>
  

    <li>
      <details>
        <summary>options: `object`</summary>
        Any additional options.
      </details>
    </li>
  
  </ul>
</details>
```

**Comment by piotretm** [comment]
Hi @Bitaru any ideas on how to solve this?

**Comment by Bitaru** [comment]
> Hi @Bitaru any ideas on how to solve this?

Hey there, sorry for the delay! Could you please create a gist with your 'custom-elements.json'? It seems to me that there might be an unclosed tag in the description.

**Comment by piotretm** [comment]
> > Hi @Bitaru any ideas on how to solve this?
> 
> Hey there, sorry for the delay! Could you please create a gist with your 'custom-elements.json'? It seems to me that there might be an unclosed tag in the description.

No worries :)

Here I've got the [gist.](https://gist.github.com/piotretm/927f51d084102644310091455a524650)

Also, the thing is that great part of this description is coming directly from [JSON Forms.](https://jsonforms.io/)

**Comment by Bitaru** [comment]
@piotretm Hey, I just pushed version [0.2.1](https://github.com/Uscreen-video/cem-plugin-better-lit-types/commit/3e1e4855e0769cc53736ea1bcf1fd4cf72f564f6). It looks like the issue was caused by Markdown processing and wrapping the entire description in a `<p>` tag.

**Comment by piotretm** [comment]
@Bitaru thanks! I've just updated the dependency and seems like this is fixing my issue. Thanks once more for your help. :)
